global:
  smtp_smarthost: 'smtp.163.com:25'　　# 163服务器
  smtp_from: 'sunx102005@163.com'　　　　　　　　#发邮件的邮箱
  smtp_auth_username: 'sunx102005@163.com'　　#发邮件的邮箱用户名，也就是你的邮箱
  smtp_auth_password: 'mx102005'　　　　　　　　#发邮件的邮箱密码
  smtp_require_tls: false　　　　　　　　# 不进行tls验证

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10m
  receiver: live-monitoring

receivers:
- name: 'live-monitoring'
  email_configs:
  - to: '1020059568@qq.com'　　　　　　　　#收邮件的邮箱