version: "3"
services:
    prometheus:
        image: prom/prometheus
        ports:
            - "9090:9090"
        volumes:
            - ./my-prometheus.yml:/etc/prometheus/prometheus.yml
        container_name: myPrometheus
